### PR TITLE
Rewrote the mod in java and removed Kotlin from the project.

### PR DESCRIPTION
**Pull request by KiriCattus**
**Advisory! Make a new branch for this Java PR to have both available to work from if needed.**

This is just a port from Kotlin to Java should anyone need a Java branch to work from if they don't know Kotlin. The mod contains two blocks and an item with some none working TE's (they did nothing in the Kotlin version either)

### CODE REVIEW

**Comment by bms-1984** [comment]
Woah.

**Comment by KiriCattus** [comment]
Long time no talk or see bms, hope you don't mind me trying to get things going again, just doing the rounds on some of MMD's mods :) if you remember what this mod was meant to be about/do would you mind leaving a small doc about it somewhere? Or would you like to return to modding sometime too?

**Comment by bms-1984** [comment]
Hey Proxy, good to see you. Doesn't bother me at all, no. I'm reasonably out of the loop when it comes to modding these days and I only intermittently have the motivation to do much computer work at all anymore, but I can't quite say it's impossible or even unlikely my interest builds. As ever though, I work in bursts. I apologize that I really don't have any design documents, as I was self-consciously anti-planning and structure when I first did this (sub-par) work. I have a vague concept of the goal however and I'd be willing to write you something up at the least.

**Comment by bms-1984** [comment]
Unfortunately, I no longer have write access to this repo.

**Comment by KiriCattus** [comment]
That might have been when the perms got resorted a while back or when the repo got transferred in, users loose access then when that happens sometimes so that would be a @jriwanek fix :3

**Comment by jriwanek** [comment]
@bms-1984 You should have an email inviting you to the repo, so.. as fixed as I can make it till you accept.

**Pull request merged**
